apiVersion: apps/v1
kind: Deployment

metadata:
    name: workflow-celery-worker

spec:
    replicas: 1

    selector:
        matchLabels:
            app: workflow-celery-worker

    template:
        metadata:
            labels:
                app: workflow-celery-worker


        spec:
            containers:
            - name: workflow-celery-worker
              image: workflow-backend:latest
              imagePullPolicy: IfNotPresent
              env:
              - name: MONGO_URI
                value: "mongodb://host.docker.internal:27017"
              - name: REDIS_HOST
                value: "redis-service"
              command:
                  - celery
                  - -A
                  - app.worker.celery_app
                  - worker
                  - --loglevel=info
                  - --concurrency=2

