from app.nodes.base import BaseNode
from app.core.config import settings

import smtplib
import os
import time

from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.application import MIMEApplication
from email.utils import formatdate


class EmailNode(BaseNode):

    def execute(
        self,
        receiver_email,
        name,
        role,
        joining_date,
        subject,
        message,
        pdf_path=None
    ):

        print("=" * 60)
        print("EMAIL NODE EXECUTED")
        print(f"Receiver : {receiver_email}")
        print(f"Name     : {name}")
        print(f"Subject  : {subject}")
        print(f"Message  : {message}")
        print("=" * 60)

        sender_email = settings.EMAIL_ADDRESS
        app_password = settings.EMAIL_PASSWORD

        if not sender_email or not app_password:
            print("Email delivery skipped: SMTP sender credentials are not configured")
            return False

        email_subject = subject if subject else "HR Workflow Notification"

        body = f"""
Dear {name},

{message}

--------------------------------------------------
Employee Details
--------------------------------------------------

Name         : {name}
Email        : {receiver_email}
Role         : {role}
Joining Date : {joining_date}

--------------------------------------------------

This email was automatically generated by the HR Workflow Studio.

Regards,

HR Team
Naxrita Solutions Private Limited

Please do not reply to this email.
"""

        msg = MIMEMultipart()

        msg["From"] = sender_email
        msg["To"] = receiver_email
        msg["Subject"] = email_subject
        msg["Reply-To"] = sender_email
        msg["Date"] = formatdate(localtime=True)

        print("Final Subject Sent:", msg["Subject"])

        msg.attach(MIMEText(body, "plain"))

        if pdf_path and os.path.exists(pdf_path):

            with open(pdf_path, "rb") as file:

                attachment = MIMEApplication(
                    file.read(),
                    _subtype="pdf"
                )

                attachment.add_header(
                    "Content-Disposition",
                    "attachment",
                    filename=os.path.basename(pdf_path)
                )

                msg.attach(attachment)

        max_retries = 3

        for attempt in range(max_retries):

            try:

                print(f"Email Attempt {attempt + 1}")

                smtp_client = smtplib.SMTP_SSL if settings.SMTP_USE_SSL else smtplib.SMTP
                server = smtp_client(settings.SMTP_HOST, settings.SMTP_PORT, timeout=15)

                server.ehlo()
                if settings.SMTP_USE_TLS and not settings.SMTP_USE_SSL:
                    server.starttls()
                    server.ehlo()

                server.login(
                    sender_email,
                    app_password
                )

                server.sendmail(
                    sender_email,
                    receiver_email,
                    msg.as_string()
                )

                server.quit()

                print("EMAIL SENT SUCCESSFULLY")
                return True

            except Exception as e:

                print(f"Email Attempt {attempt + 1} Failed")
                print("Error:", e)

                if attempt < max_retries - 1:
                    print("Retrying in 2 seconds...")
                    time.sleep(2)

        print("Email failed after all retry attempts")
        return False

    async def compensate(self, context):

        print(
            f"[SAGA] Compensation executed for Email Node : {self.node_id}"
        )
